2019-02-19 23:07:56,568 ERROR: Exception on /explore [GET] [in /Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/brianlouie/Desktop/microblog/app/routes.py", line 41, in explore
    if posts.has_next else None
NameError: name 'post' is not defined
2019-02-19 23:08:01,568 ERROR: Exception on /explore [GET] [in /Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/brianlouie/Desktop/microblog/app/routes.py", line 41, in explore
    if posts.has_next else None
NameError: name 'post' is not defined
2019-02-19 23:19:13,895 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-02-21 21:04:51,322 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:45]
2019-03-10 18:57:32,885 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-03-10 19:04:01,378 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-03-10 19:14:37,837 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-03-16 08:31:59,246 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-03-16 08:33:19,323 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-03-16 08:36:09,699 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-04-03 21:43:45,249 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-04-03 22:00:22,851 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-04-04 23:24:58,361 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-04-04 23:36:41,295 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-04-04 23:40:38,090 ERROR: Exception on /reset_password_request [POST] [in /Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/brianlouie/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/brianlouie/Desktop/microblog/app/routes.py", line 159, in reset_password_request
    user = User.quality.filter_by(email=form.email.data).first()
AttributeError: type object 'User' has no attribute 'quality'
2019-04-04 23:42:38,343 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:47]
2019-04-06 12:21:40,462 INFO: Microblog startup [in /Users/brianlouie/Desktop/microblog/app/__init__.py:48]
